version: '3.2'
services:
  opcuapepicsbridge:
    build:
      context: ./
      dockerfile: docker/opcuaEpicsBridge/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    env_file: .env
    environment:
      - name=OpcuaTest1
      - url=opc.tcp://test_user@0.0.0.0:4840
      - subscriptionRate=1000
      # - debug=True
      - secure=True
    volumes:
      - ./certificates:/certificates/
      - ./db/test.db:/bridge/bridge.db
      
  