version: '3.2'
services:
  opcuapepicsbridge:
    build:
      context: ./
      dockerfile: docker/opcuaEpicsBridge/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - name=OpcuaTest1
      - url=opc.tcp://test_user@0.0.0.0:4840
      - subscriptionRate=100
      # - debug=True
      - secure=True
    command: "/bin/sh -c 'sleep 5; python bridge.py;'"
    volumes:
      - ./certificates:/certificates/
      - ./db/test.db:/bridge/bridge.db
  
  opcuapythonserver:
    build:
      context: ./
      dockerfile: docker/opcuaSimple/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    command: "/bin/sh -c 'python server-minimal.py;'"
    environment:
      - secure=True
    volumes:
      - ./certificates:/certificates/
      
  