version: '3.2'
services:
  opcuapepicsbridge:
    build:
      context: ./
      dockerfile: docker/opcuaEpicsBridge/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    env_file: .env
    environment:
      - name=OpcuaTest1
      - url=opc.tcp://192.168.56.104:4840
      - subscriptionRate=1000
      # - debug=True
      - secure=False
    volumes:
      - ./certificates:/certificates/
      - ./db/testBeckhoff.db:/bridge/bridge.db
  